[package]
name = "rs-grooming"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
itertools = "0.13"
regex = "1.11"
reqwest = "0.12"
tokio = { version = "1.41", features = ["full"] }
